### ISSUE TITLE
Email when service autoscales and / or alarm triggers

### ISSUE THREAD

**Issue by dkatzz** [cn-terraform/terraform-aws-ecs-service-autoscaling#28]
It would be nice if there was an optional email variable that could be set, so that the email provided could get notified when the service autoscales or the alarm triggers. This could also be done by having a variable for a sns topic arn if that is easier and if set it gets added to the alarm actions as well.

**Comment by mayank0202** [comment]
https://github.com/cn-terraform/terraform-aws-ecs-service-autoscaling/pull/31

I have added sns variable as an optional variable so that should work @dkatzz @jnonino

**Comment by jnonino** [comment]
Hi @dkatzz and @mayank0202, considering the change by @mayank0202 released in version 1.0.7. Do you think we can close this issue?

**Comment by mayank0202** [comment]
@jnonino  We can close this issue , its working fine . please use 1.0.8 version

**Comment by jnonino** [comment]
Thank you!!!

**Comment by dkatzz** [comment]
Thank you for making these changes!!
